# frozen_string_literal: true

source 'https://rubygems.org'

gem 'debug', '>= 1.0.0'
gem 'minitest'
gem 'minitest-focus'
gem 'minitest-reporters'

gem 'ruby-prof'

group :development do
  gem 'rubocop'
end
