# frozen_string_literal: true

source 'https://rubygems.org'

gem 'debug', '>= 1.0.0'
gem 'paint'
gem 'ruby-prof'

group :test do
  gem 'minitest'
  gem 'minitest-focus'
  gem 'minitest-reporters'
end

group :development do
  gem 'rubocop'
end
